ansible:
  - ansible/**/*

cheatsheets:
  - cheatsheets/**/*

docker-compose:
  - docker-compose/**/*

docker:
  - docker/**/*

scripts:
  - scripts/**/*

terraform:
  - terraform/**/*

documentation:
  - '*.md'
  - '*.markdown'

ci/cd:
  - .github/workflows/*
  - .pre-commit-config.yaml
