ansible-roles:
  - ansible-roles/**/*

docker-compose:
  - docker-compose/**/*

docker-images:
  - docker-images/**/*

scripts:
  - scripts/**/*

documentation:
  - '*.md'
  - '*.markdown'

ci/cd:
  - .github/workflows/*
  - .pre-commit-config.yaml
