---
# ----------------------------------------------------------------------------------------
# INSTALL
# ----------------------------------------------------------------------------------------
- name: Install Metasploit
  apt: pkg={{item}} state=present update_cache=true
  register: msf
  with_items:
    - metasploit-framework
    - armitage

- name: Create support folders
  file: path=~/.msf4/modules/{{item}} state=directory
  with_items:
    - auxiliary
    - exploits
    - payloads
    - post

#--- Fix permissions - 'could not translate host name "localhost", service "5432" to address: Name or service not known'
- name: Fix permissions on /etc/hosts file
  file: dest=/etc/hosts mode=0644
  register: postgresql
  notify:
    - Reload PostgreSQL


# ----------------------------------------------------------------------------------------
# SETUP DB
# ----------------------------------------------------------------------------------------
- name: Autostart postgresql on boot
  when: postgresql is success
  shell: sudo update-rc.d postgresql enable

- name: MSFDB Reinit
  when: postgresql is success
  register: reinit
  shell:  |
    msfdb reinit
    sleep 5s

- name: First time run with Metasploit
  when: reinit is success
  register: firstrun
  shell: |
    systemctl start postgresql
    msfdb start
    msfconsole -q -x 'version;db_status;sleep 310;exit'


# ----------------------------------------------------------------------------------------
# CONFIG
# ----------------------------------------------------------------------------------------
- name: Autorun Metasploit commands each startup (msf_autorunscript.rc)
  when: firstrun is success
  copy:
    src: "{{ role_path }}/files/msf_autorunscript.rc"
    dest: ~/.msf4/msf_autorunscript.rc
    mode: a+x

- name: Autorun Metasploit commands each startup (msfconsole.rc)
  when: firstrun is success
  copy:
    src: "{{ role_path }}/files/msfconsole.rc"
    dest: ~/.msf4/msfconsole.rc
    mode: a+x

- name: Generate payload list
  when: firstrun is success
  command: "{{item}}"
  with_items:
    - mkdir -p ~/.msf4/msfvenom/
    - msfvenom --list nops > ~/.msf4/msfvenom/nops
    - msfvenom --list payloads > ~/.msf4/msfvenom/payloads
    - msfvenom --list encoders > ~/.msf4/msfvenom/encoders
    - msfvenom --list formats > ~/.msf4/msfvenom/formats

- name: Setup bash aliases
  when: firstrun is success
  script: ../files/aliases.sh

- name: Setup Armitage
  when: firstrun is success
  script: ../files/armitage.sh