---
# ==============================================================================
# Installation sources
# ==============================================================================
- name: Install Tools via pip
  register: pip_done
  sudo: true
  pip: name={{ item }}
  with_items:
    - '{{ dev_pip|default([]) }}'

- name: Install Tools via easy_install
  when: pip_done is success
  register: easy_install_done
  sudo: true
  easy_install: name={{ item }}
  with_items:
    - '{{ dev_easy_install|default([]) }}'

- name: Install Tools via gem
  when: easy_install_done is success
  register: gem_done
  sudo: true
  gem: name={{ item.package }}
    state={{ item.state|default("latest") }}
  with_items:
    - '{{ dev_gem|default([]) }}'

- name: Install Tools via go
  when: gem_done is success
  register: go_done
  sudo: true
  shell: go get {{ item }}
  with_items:
    - '{{ dev_go|default([]) }}'

- name: Clone GIT repositories
  when: go_done is success
  register: git_done
  git: repo={{ item.repo }}
    dest={{tools_dir}}/{{ item.dest }}
    accept_hostkey=yes
    version={{ item.version|default(\"master\") }}
    force={{ item.force|default("no") }}
  with_items:
    - '{{ dev_git_repositories|default([]) }}'

- name: Download binaries
  when: git_done is success
  register: bin_done
  get_url: url={{ item.url }}
    dest={{ item.dest }}
    mode=a+x
  with_items:
    - '{{ dev_binary|default([]) }}'

- name: Download and extract zipped installs
  when: git_done is success
  register: tars_done
  unarchive: src={{ item.src }}
    dest={{ item.dest}}
    remote_src=yes
  with_items:
    - '{{ dev_tars|default([]) }}'

- name: Install Tools via brew
  when: git_done is success
  register: brew_done
  shell: brew install {{ item }}
  with_items:
    - '{{ dev_brew|default([]) }}'

# ==============================================================================
# Config files
# ==============================================================================
# ---------- ZSH
- name: Execute the zsh-installer.sh
  when: tars_done is success
  register: zsh_done
  script: /tmp/zsh-installer.sh

- name: Set ZSH as default shell
  when: zsh_done is success
  command: chsh -s "$(which zsh)"

# ---------- CONFIG
- name: Copy configuration files
  when: zsh_done is success
  copy:
    src: '{{ role_path }}/files/{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - '{{ dev_config|default([]) }}'

# ==============================================================================
# Custom setup
# ==============================================================================
- name: Install zsh-autosuggestions
  when: zsh_done is success
  command: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# ==============================================================================
# CLEANUP
# ==============================================================================
- debug: msg="{{ item }}"
  with_items:
    - 'Install iTerm2 color scheme (Bluloco Dark) from /tmp/iTerm2-Color-Schemes/'
    - 'Import iTerm2 Material from /tmp/iterm-material.json'
