name: 'Docker Push to GCR'
description: 'Docker Push to GCR'

inputs:
  image_local:
    description: 'Name of the local image built'
    required: true
  image_remote:
    description: 'Name of the remote image to push'
    required: true
  registry:
    description: 'GCR registry'
    required: true
  version_file:
    description: 'Path of the file containing the VERSION number'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 📊 Obtain version
      id: obtain_version
      shell: bash
      run: |
        version=$(cat ${{ inputs.version_file }})
        echo "🎉 Found version: ${version}"
        echo "::set-output name=tag::$version"

    - name: 🚀 Push image to GitHub Container Registry
      id: push
      shell: bash
      run: |
        REMOTE_IMAGE=${{ inputs.registry }}/${{ inputs.image_remote }}
        IMAGE_VERSION=${{ steps.obtain_version.outputs.tag }}

        echo "🏷 Tagging image"
        docker tag ${{ inputs.image_local }} ${REMOTE_IMAGE}:${IMAGE_VERSION}
        docker tag ${{ inputs.image_local }} ${REMOTE_IMAGE}:latest

        echo "⚙️ Pushing ${REMOTE_IMAGE}:${IMAGE_VERSION}"
        docker push ${REMOTE_IMAGE}:${IMAGE_VERSION}

        echo "⚙️ Pushing ${REMOTE_IMAGE}:latest"
        docker push ${REMOTE_IMAGE}:latest
