# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="custom"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-extras tmux last-working-dir dirhistory python pip z docker)
source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='micro'
else
  export EDITOR='micro'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# ------------------------------------------------------------------------------
#  CUSTOM
# ------------------------------------------------------------------------------
eval "$(starship init zsh)"
eval "$(mcfly init zsh)"
source ~/.config/broot/launcher/bash/br

# Setting history length
HISTSIZE=1000000
HISTFILESIZE=2000000
HISTTIMEFORMAT="%d/%m/%y %T "

# Individual history per terminal
unsetopt inc_append_history
unsetopt share_history

# Fuzzy bash completion
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Cd
function cd {
    # builtin cd "$@" && clear && ls -lh
    builtin cd "$@" && clear && exa -l --git
}
# alias la='ls -A'
alias la='ls exa -la --git'
# alias ls='clear && ls -lhG'
alias ls="clear && exa -l --git"
alias ..="cd .."
alias ee="exit"

# Networking
alias renew='/etc/init.d/networking restart'
alias openports="sudo lsof -PiTCP -sTCP:LISTEN"

# GIT
alias branches="git ls-remote --heads github"
alias master="gco master && gl"
alias main="gco main && gl"
alias glog="git log --graph --decorate --oneline"
alias glog_full="git log --graph --decorate --abbrev-commit"
alias git_changelog="git log github/main..HEAD --format='* %s%n%w(,4,4)%+b'"
alias ungit='/usr/bin/find . -type d \( -path \*.terraform \) -prune -false -o -name ".git" | while read dir ; do sh -c "cd $dir/../ && echo \"\n🗂  GIT STATUS IN ${dir//\.\git/}\" && git status -s && (git status -u | grep behind) && git cherry -v" ; done'

# Override old commands
alias lock="gnome-screensaver-command -l"
alias emacs="emacs -nw"
alias bat='bat --theme TwoDark'
alias du="duf"
alias ping="gping"
alias curl="curlie"
alias find="fd"
alias ps="procs"
alias d="lima nerdctl"

# Python
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export PYTHONSTARTUP=/root/.pythonstartup
export PIPENV_VENV_IN_PROJECT=true

# Ruby
# export PATH="$HOME/.rvm:$PATH"
# export PATH="$PATH:$HOME/.rvm/bin"
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Go
export GOPATH=~/go/

# Plz
source ~/.profile
source <(plz --completion_script)

# CSPs
export AWS_SDK_LOAD_CONFIG=1
source /usr/local/bin/aws_zsh_completer.sh
source /usr/lib/google-cloud-sdk/completion.bash.inc
alias awslocal="aws --endpoint-url=http://localhost:4566 --profile localstack --region us-east-1"

# Kubernetes
source <(kubectl completion zsh)
# https://github.com/ahmetb/kubectl-aliases
[ -f ~/.kube/kubectl_aliases ] && source ~/.kube/kubectl_aliases
[ -f ~/.kubectl_aliases ] && source ~/.kubectl_aliases
function kubectl() { echo "+ kubectl $@">&2; command kubectl $@; }
alias k="kubectl"
alias krew="kubectl-krew"
alias k_debug_shell="kubectl run -it --rm --restart=Never debug-shell --image alpine -- sh"
export KUBE_PS1_PREFIX="["
export KUBE_PS1_SUFFIX="]"
export KUBE_PS1_SEPARATOR="|"
export KUBE_PS1_CTX_COLOR="magenta"
export KUBE_PS1_NS_COLOR="cyan"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:~/go/bin:$PATH"
export KUBECONFIG=~/.kube/config
for file in ~/.kube/configs/*.yaml; do
    export KUBECONFIG=$KUBECONFIG:$file
done
complete -F __start_kubectl k
# source ~/.oh-my-zsh/custom/kube-ps1.sh

#
# Compinit
#
# autoload -U compinit && compinit
autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C

# Yubikey SSH GPG
# export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh
# gpg-connect-agent updatestartuptty /bye > /dev/null
