---
CODE_SERVER_VERSION: '3.3.0'

# VSCODE
dev_binary:
  - url: https://code.visualstudio.com/docs/?dv=linux64_deb
    dest: '/tmp/vscode.deb'

dev_deb:
  - /tmp/vscode.deb

dev_config:
  - src: 'settings.json'
    dest: '~/.config/Code/User/settings.json'
  - src: 'extensions'
    dest: '/tmp/extensions'

# CODE SERVER
dev_tars:
  - src: 'https://github.com/cdr/code-server/releases/download/v{{ CODE_SERVER_VERSION }}/code-server-{{ CODE_SERVER_VERSION }}-linux-amd64.tar.gz'
    dest: '/opts/vscode-server/'
