name: 'Trivy'
description: 'Trivy'

inputs:
  image_name:
    description: 'Name of the image'
    required: true

runs:
  using: 'composite'
  steps:
    #
    # Scan
    #
    - name: 🛡 Run Trivy vulnerability scanner
      # TODO: currently not allowed in composite actions
      # continue-on-error: true
      uses: aquasecurity/trivy-action@0.0.20
      id: scan
      with:
        image-ref: ${{ inputs.image_name }}
        format: 'table'
        # WARN ONLY
        exit-code: '0'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
