name: '[DOCKER IMAGE] Pandoc'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docker/pandoc/Dockerfile'
      - 'docker/pandoc/VERSION'
  pull_request:
    branches:
      - main
    paths:
      - 'docker/pandoc/Dockerfile'
      - 'docker/pandoc/VERSION'

jobs:
  run-docker:
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    uses: marco-lancini/utils/.github/workflows/reusable-docker.yml@main
    with:
      FOLDER: ${{ github.workspace }}/docker/pandoc
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_NAME: pandoc
    secrets:
      GHCR_USER: ${{ github.repository_owner }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
