name: '[DOCKER IMAGE] Markserv'

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
  push:
    branches:
      - main
    paths:
      - 'docker/markserv/Dockerfile'
      - 'docker/markserv/VERSION'
  pull_request:
    branches:
      - main
    paths:
      - 'docker/markserv/Dockerfile'
      - 'docker/markserv/VERSION'

jobs:
  run-docker:
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    uses: marco-lancini/utils/.github/workflows/reusable-docker.yml@main
    with:
      FOLDER: ${{ github.workspace }}/docker/markserv
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_NAME: markserv
    secrets:
      GHCR_USER: ${{ github.repository_owner }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
